# Generated by Django 4.2.3 on 2023-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
