# Generated by Django 4.2.3 on 2023-07-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_role_patient_healthworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworker',
            name='fullname',
        ),
        migrations.AddField(
            model_name='healthworker',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthworker',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
