# Generated by Django 4.2.2 on 2023-07-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_doctor_sharedaccess_healthworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccess',
            name='owner_healthprovider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
