# Generated by Django 4.2.2 on 2023-07-21 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_sharedaccess_owner_healthprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedaccess',
            name='healthworker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_healthworker', to='myapp.healthworker'),
        ),
        migrations.AlterField(
            model_name='sharedaccess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedaccess',
            name='owner_healthprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_healthprovider', to='myapp.healthprovider'),
        ),
        migrations.AlterField(
            model_name='sharedaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_patient', to='myapp.patient'),
        ),
    ]
