# Generated by Django 4.2.2 on 2023-07-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sharedaccess_verified_userkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedaccess',
            old_name='verified',
            new_name='isverified',
        ),
    ]
